### ISSUE TITLE
If the d3d device doesn't support raytracing, the program will crash with an access violation instead of showing an alert

### ISSUE THREAD

**Issue by tobiasmarciszko** [boksajak/referencePT#1]
The check if the d3d.device is nullptr or not is done inside the for loop in CreateDevice. If it's placed after the iteration of adapters, the check will be carried out if there is not device with raytracing support.

https://github.com/boksajak/referencePT/blob/b5eff926bc1ffc8550a475ce4a2b4c3ca1ad320e/src/Graphics.cpp#L733

![image](https://user-images.githubusercontent.com/9927019/125052940-cb991e00-e0a4-11eb-9ec9-d028bfc3859e.png)

**Comment by tobiasmarciszko** [comment]
Sadly enough, the first computer I tried this on didn't have the raytracing features enabled...

**Comment by boksajak** [comment]
thanks for pointing this out! It's now been fixed.
