### ISSUE TITLE
InstanceID is 24 bit total, not 32, this could cause issues with large scenes duo to packing

### ISSUE THREAD

**Issue by zuba** [boksajak/referencePT#2]
Hello, I was reading preprint of the book(RT Gems II, Chapter 14), and there's a mistake about InstanceID variable, as DXR spec says,
it's 24 bit total, but bindless indices are store in the upper and lower 16 bits, this could cause issues if there will be more than 256 unique geometries(you have only 8 bits for upper indices), maybe you can split it 12/12 bits to solve this issue. Hope this will help. 

P.S. Here's the link to DXR spec reference
https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#instanceid

**Comment by boksajak** [comment]
Good catch, thanks! We've adjusted it to 14/10 bits to support more instances than materials, which might be more common. But of course - this has to be adjusted for requirements of given scene/engine etc. Even the indirection via some index buffer might be necessary for largest scenes.
